server:
  port: 8080

etwas:
  swagger-open: true              #是否开启swagger (true/false)
  kaptcha-open: true             #是否开启登录时验证码 (true/false)
#  file-upload-path: d:/tmp       #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

spring:
  datasource:
    url: jdbc:mysql://47.116.77.115:3336/etwas-test?autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
    username: test_user
    password: q3454V@wV
    db-name: etwas-test #用来搜集数据库的所有表
    filters: wall,mergeStat
    connectionInitSqls: set names utf8mb4;
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  redis:
      host: 47.116.77.115
      #redis密码，没有密码的可以用～表示
      password: etwas@123
      port: 6369

#微信配置
wx:
   # 小程序
  small-program:
    appid: wx322d222ddf831ddf
    secret: df44f886e679d586bce22cdaa1e7d056
    token:
    aesKey:
    msgDataFormat: JSON

mybatis-plus:
  typeAliasesPackage: com.cola.magazine.modular.system.model
  global-config:
    logic-delete-value: 1
    logic-not-delete-value: 0 #逻辑删除配置
log:
  path: admin-logs

qiniu:
  bucket: etwas
  bucket-url: https://static.etwas.cn/
  pipeline:
  notify-host: