server:
  port: 8080

etwas:
  swagger-open: true              #是否开启swagger (true/false)
  kaptcha-open: true             #是否开启登录时验证码 (true/false)
#  file-upload-path: d:/tmp       #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒


spring:
  datasource:
    url: jdbc:mysql://172.28.179.219:3336/etwas?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
    username: prod_user
    password: M1RtVhPj@V
    db-name: etwas #用来搜集数据库的所有表
    filters: wall,mergeStat
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  redis:
      host: 172.28.179.219
      #redis密码，没有密码的可以用～表示
      password: etwas@123
      port: 6369

mybatis-plus:
  typeAliasesPackage: com.cola.magazine.modular.system.model
  global-config:
    logic-delete-value: 1
    logic-not-delete-value: 0 #逻辑删除配置
log:
  path: admin-logs


#微信配置
wx:
 # 公众号-订阅号
  subscription-number:
    appid:
    secret:
    token:
    aesKey:
    msgDataFormat: JSON
  service-number:
    appid: wx6e05fdd64464b8f8
    secret: 780eff17b6bbac86ea475eaf88263ee6
    token:
    aesKey:
    msgDataFormat: JSON
   # 小程序
  small-program:
    appid: wx322d222ddf831ddf
    secret: df44f886e679d586bce22cdaa1e7d056
    token:
    aesKey:
    msgDataFormat: JSON
  # 微信支付
  wx-pay:
    #微信公众号或者小程序等的appid
    appId:
    #微信支付商户号
    mchId: 1601487702
    #微信支付商户密钥
    mchKey: 08FA5C1C4C164908AC0A79EA224FEDA6
    #服务商模式下的子商户公众账号ID
    subAppId:
    #服务商模式下的子商户号
    subMchId:
    # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    keyPath: classpath:/apiclient_cert.p12

#多数据源情况的配置
magazine:
  muti-datasource:
    open: false
    url: jdbc:mysql://127.0.0.1:3306/guns_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    dataSourceNames:
      - dataSourceGuns
      - dataSourceBiz
qiniu:
  bucket: etwas
  bucket-url: https://static.etwas.cn/
  pipeline:
  notify-host: