rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: etwas321        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: etwas123      #md5加密混淆key

server:
  port: 8081 #项目端口

mybatis-plus:
  typeAliasesPackage: com.cola.magazine.modular.system.model

spring:
  datasource:
      url: jdbc:mysql://47.116.77.115:3336/etwas-test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
      username: test_user
      password: q3454V@wV
      filters: log4j,wall,mergeStat
  redis:
    host: 47.116.77.115
    #redis密码，没有密码的可以用～表示
    password: etwas@123
    port: 6369
logging:
  level.root: info
  level.com.cola: debug
  path: logs/
  file: ./etwas-rest.log


#微信配置
wx:
 # 公众号
  mp:
    appid: wxb7194003cf097d0c
    secret: 79b6bcf9a6e6ab060ecbf3dcc0c19f2f
    token:
    aesKey:
    msgDataFormat: JSON
  # 小程序
  small-program:
    appid: wx322d222ddf831ddf
    secret: df44f886e679d586bce22cdaa1e7d056
    token:
    aesKey:
    msgDataFormat: JSON
  # 微信支付
  wx-pay:
    #微信公众号或者小程序等的appid
    appId:
    #微信支付商户号
    mchId: 1602970477
    #微信支付商户密钥
    mchKey: 04618D199DA1DA2AC33B5A7054855913
    #服务商模式下的子商户公众账号ID
    subAppId:
    #服务商模式下的子商户号
    subMchId:
    # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    keyPath: classpath:/apiclient_cert.p12
    # 支付成功后回调的url
    notifyUrl: https://api.etwas.cn/wx/pay/notify/order
  # 开放平台
  zowm:
    componentAppId:
    componentSecret:
    componentToken: ""
    componentAesKey: ""

qiniu:
  bucket: etwas
  bucket-url: https://static.etwas.cn/
  pipeline:
  notify-host: